//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trabalho_SIGE.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Banco_Conexao_Entities : DbContext
    {
        public Banco_Conexao_Entities()
            : base("name=Banco_Conexao_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Conta> Conta { get; set; }
        public virtual DbSet<Conta_Pagar> Conta_Pagar { get; set; }
        public virtual DbSet<Conta_Receber> Conta_Receber { get; set; }
        public virtual DbSet<Setor> Setor { get; set; }
        public virtual DbSet<Solicitacao_de_Compra> Solicitacao_de_Compra { get; set; }
        public virtual DbSet<Tipo_Conta> Tipo_Conta { get; set; }
        public virtual DbSet<Tipo_Transacao> Tipo_Transacao { get; set; }
        public virtual DbSet<Transacao> Transacao { get; set; }
        public virtual DbSet<Transacao_Conta_Pagar> Transacao_Conta_Pagar { get; set; }
        public virtual DbSet<Transacao_Conta_Receber> Transacao_Conta_Receber { get; set; }
        public virtual DbSet<Pedidos> Pedidos { get; set; }
        public virtual DbSet<Produto> Produto { get; set; }
        public virtual DbSet<Evento> Evento { get; set; }
        public virtual DbSet<Vendas> Vendas { get; set; }
        public virtual DbSet<Registro_De_Venda> Registro_De_Venda { get; set; }
        public virtual DbSet<Producao> Producao { get; set; }
    }
}
