//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trabalho_SIGE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conta_Pagar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Conta_Pagar()
        {
            this.Solicitacao_de_Compra = new HashSet<Solicitacao_de_Compra>();
            this.Transacao_Conta_Pagar = new HashSet<Transacao_Conta_Pagar>();
        }
    
        public int id { get; set; }
        public System.DateTime vencimento { get; set; }
        public decimal valor { get; set; }
        public int idTipo { get; set; }
        public Nullable<int> idSetor { get; set; }
    
        public virtual Tipo_Conta Tipo_Conta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Solicitacao_de_Compra> Solicitacao_de_Compra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transacao_Conta_Pagar> Transacao_Conta_Pagar { get; set; }
        public virtual Setor Setor { get; set; }
    }
}
