//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trabalho_SIGE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conta_Receber
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Conta_Receber()
        {
            this.Transacao_Conta_Receber = new HashSet<Transacao_Conta_Receber>();
            this.Registro_De_Venda = new HashSet<Registro_De_Venda>();
        }
    
        public int id { get; set; }
        public System.DateTime vencimento { get; set; }
        public decimal valor { get; set; }
        public int idTipo { get; set; }
    
        public virtual Tipo_Conta Tipo_Conta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transacao_Conta_Receber> Transacao_Conta_Receber { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Registro_De_Venda> Registro_De_Venda { get; set; }
    }
}
