//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trabalho_SIGE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evento
    {
        public int id { get; set; }
        public int idEvento { get; set; }
        public decimal orcamento { get; set; }
        public decimal gasto { get; set; }
        public string fornecedor { get; set; }
        public int idSetor { get; set; }
        public Nullable<System.DateTime> data { get; set; }
    
        public virtual Setor Setor { get; set; }
    }
}
