//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trabalho_SIGE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registro_De_Venda
    {
        public int id { get; set; }
        public string codRegistro { get; set; }
        public decimal valor { get; set; }
        public System.DateTime data { get; set; }
        public int idContaReceber { get; set; }
    
        public virtual Conta_Receber Conta_Receber { get; set; }
    }
}
