//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trabalho_SIGE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solicitacao_de_Compra
    {
        public int id { get; set; }
        public int idSetor { get; set; }
        public string descricao { get; set; }
        public System.DateTime dataPedido { get; set; }
        public System.DateTime dataVencimento { get; set; }
        public bool aprovada { get; set; }
        public Nullable<int> idContaPagar { get; set; }
        public decimal valor { get; set; }
    
        public virtual Conta_Pagar Conta_Pagar { get; set; }
        public virtual Setor Setor { get; set; }
    }
}
