//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trabalho_SIGE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transacao_Conta_Receber
    {
        public int id { get; set; }
        public int idConta { get; set; }
        public int idTransacao { get; set; }
    
        public virtual Conta_Receber Conta_Receber { get; set; }
        public virtual Transacao Transacao { get; set; }
    }
}
