//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trabalho_SIGE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transacao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transacao()
        {
            this.Transacao_Conta_Pagar = new HashSet<Transacao_Conta_Pagar>();
            this.Transacao_Conta_Receber = new HashSet<Transacao_Conta_Receber>();
        }
    
        public int id { get; set; }
        public int idTipo { get; set; }
        public System.DateTime data { get; set; }
        public decimal valor { get; set; }
        public int idConta { get; set; }
    
        public virtual Tipo_Transacao Tipo_Transacao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transacao_Conta_Pagar> Transacao_Conta_Pagar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transacao_Conta_Receber> Transacao_Conta_Receber { get; set; }
        public virtual Conta Conta { get; set; }
    }
}
