//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trabalho_SIGE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendas
    {
        public int id { get; set; }
        public int idVenda { get; set; }
        public decimal valor { get; set; }
        public Nullable<System.DateTime> data { get; set; }
    }
}
